#CDEBUG = -g -Wall -fsanitize=address
#LDEBUG = -g -lasan

CDEBUG = -g -Wall
LDEBUG = -g

PROG = CQRayTraceApp

CPP_SRC = \
Camera.cpp \
Canvas.cpp \
Color.cpp \
Cone.cpp \
CSG.cpp \
Cube.cpp \
Cylinder.cpp \
Group.cpp \
IntersectionData.cpp \
Light.cpp \
Material.cpp \
Matrix4D.cpp \
Object.cpp \
ObjFile.cpp \
Pattern.cpp \
Ray.cpp \
RayTrace.cpp \
Sphere.cpp \
World.cpp \

EXTRA_CFLAGS = \

include $(MAKE_DIR)/lib.mk
