CDEBUG = -g -Wall -fsanitize=address
LDEBUG = -g -lasan

PROG = CQRayTraceTest

CPP_SRC = \
CQRayTraceTest.cpp \
Camera.cpp \
Canvas.cpp \
Color.cpp \
Cone.cpp \
Cube.cpp \
Cylinder.cpp \
Group.cpp \
IntersectionData.cpp \
Light.cpp \
Material.cpp \
Matrix4D.cpp \
Object.cpp \
Pattern.cpp \
Ray.cpp \
RayTrace.cpp \
Sphere.cpp \
World.cpp \

EXTRA_CFLAGS = \

include $(MAKE_DIR)/bin.mk
